<script>
    import { round } from '$lib/utils/helper';
    import { getTeamFromTeamManagers } from '$lib/utils/helperFunctions/universalFunctions';
    export let matchupArray=[]; export let players={}; export let displayWeek; export let year; export let leagueTeamManagers;
    const numericRound=(v)=>Number(round(Number(v)||0));
    const sum=(v=[])=>v.reduce((t,n)=>t+(Number(n)||0),0);
    const actual=(e)=>numericRound(sum(e?.points||[]));
    const safeTeam=(id)=>{try{return getTeamFromTeamManagers(leagueTeamManagers,Number(id),year)}catch(e){return{name:`Team ${id}`}}};
    const projection=(e)=>numericRound((e?.starters||[]).reduce((t,id)=>{const v=Number(players?.[id]?.wi?.[displayWeek]?.p);return t+(Number.isFinite(v)?v:0)},0));
    const playerName=(id)=>{const p=players?.[id];if(!p)return`Player ${id}`;if(p.pos==='DEF')return p.ln||p.fn||String(id).toUpperCase();return`${p.fn||''} ${p.ln||''}`.trim()||`Player ${id}`};
    const topScorer=(e)=>{const s=e?.starters||[],pts=e?.points||[];let best=null;s.forEach((id,i)=>{const score=Number(pts[i]||0);if(!id||id==0||score<=0)return;if(!best||score>best.points)best={name:playerName(id),points:numericRound(score)}});return best};
    const makeUpdate=(m)=>{const one=m?.[0],two=m?.[1];if(!one||!two)return null;const teamOne=safeTeam(one.roster_id),teamTwo=safeTeam(two.roster_id),scoreOne=actual(one),scoreTwo=actual(two),projectionOne=projection(one),projectionTwo=projection(two),leader=scoreOne===scoreTwo?null:scoreOne>scoreTwo?teamOne:teamTwo,lead=numericRound(Math.abs(scoreOne-scoreTwo)),a=topScorer(one),b=topScorer(two),top=!a?b:!b?a:a.points>=b.points?a:b;return{teamOne,teamTwo,scoreOne,scoreTwo,projectionOne,projectionTwo,top,text:leader?`${leader.name} currently leads by ${lead} points.${top?` ${top.name} is the matchup's top scorer so far with ${top.points}.`:''}`:`${teamOne.name} and ${teamTwo.name} are currently tied.${top?` ${top.name} is the matchup's top scorer so far with ${top.points}.`:''}`}};
    $: updates=(matchupArray||[]).map(makeUpdate).filter(Boolean);
    $: highest=updates.flatMap(i=>[{team:i.teamOne,points:i.scoreOne},{team:i.teamTwo,points:i.scoreTwo}]).sort((a,b)=>b.points-a.points)[0];
    $: closest=[...updates].sort((a,b)=>Math.abs(a.scoreOne-a.scoreTwo)-Math.abs(b.scoreOne-b.scoreTwo))[0];
</script>
<style>
.liveCard{width:95%;max-width:900px;margin:0 auto 24px;padding:20px;box-sizing:border-box;border:1px solid var(--ccc);border-radius:16px;background:var(--fff);box-shadow:0 4px 14px rgba(0,0,0,.06)}.header{text-align:center;margin-bottom:16px}.eyebrow{font-size:.72rem;font-weight:800;letter-spacing:1px;text-transform:uppercase;opacity:.55}h4{margin:5px 0 0;font-size:1.35rem}.sub{margin-top:5px;font-size:.7rem;opacity:.55}.summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-bottom:16px}.summaryItem{padding:12px;border-radius:12px;background:var(--f3f3f3);text-align:center}.label{font-size:.65rem;font-weight:800;text-transform:uppercase;letter-spacing:.4px;opacity:.55}.value{margin-top:4px;font-size:.86rem;font-weight:850}.games{display:grid;gap:10px}.game{padding:13px 14px;border-radius:12px;background:var(--f3f3f3)}.scoreLine{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:8px;font-weight:850}.teamOne{text-align:right;min-width:0}.teamTwo{text-align:left;min-width:0}.score{white-space:nowrap;font-size:1.05rem}.projections{margin-top:5px;text-align:center;font-size:.67rem;opacity:.55}.note{margin-top:8px;text-align:center;font-size:.78rem;line-height:1.4}@media(max-width:600px){.liveCard{width:100%;padding:15px 12px}.scoreLine{font-size:.8rem}.score{font-size:.95rem}.note{font-size:.73rem}}
</style>
{#if updates.length}
<section class="liveCard"><div class="header"><div class="eyebrow">Live Week {displayWeek} Update</div><h4>🏈 Matchups In Progress</h4><div class="sub">Latest scoring from Sleeper</div></div><div class="summary"><div class="summaryItem"><div class="label">Highest Score So Far</div><div class="value">{highest?.team?.name||'—'} · {highest?.points??0}</div></div><div class="summaryItem"><div class="label">Closest Game</div><div class="value">{closest?numericRound(Math.abs(closest.scoreOne-closest.scoreTwo)):0} pts</div></div></div><div class="games">{#each updates as item}<div class="game"><div class="scoreLine"><div class="teamOne">{item.teamOne.name}</div><div class="score">{item.scoreOne} – {item.scoreTwo}</div><div class="teamTwo">{item.teamTwo.name}</div></div><div class="projections">Pregame projection: {item.projectionOne} – {item.projectionTwo}</div><div class="note">{item.text}</div></div>{/each}</div></section>
{/if}