<script>
 import { round } from '$lib/utils/helper';
 import { getTeamFromTeamManagers } from '$lib/utils/helperFunctions/universalFunctions';
 export let matchupArray=[]; export let matchupWeeks=[]; export let displayWeek; export let players={}; export let year; export let leagueTeamManagers;
 const n=v=>Number(round(Number(v)||0)); const sum=a=>(a||[]).reduce((t,v)=>t+(Number(v)||0),0);
 const team=id=>{try{return getTeamFromTeamManagers(leagueTeamManagers,Number(id),year)||{name:`Team ${id}`}}catch(e){return{name:`Team ${id}`}}};
 const proj=e=>(e?.starters||[]).reduce((t,id)=>t+(Number(players?.[id]?.wi?.[displayWeek]?.p)||0),0);
 const game=(id,w)=>{const wd=(matchupWeeks||[]).find(x=>Number(x.week)===Number(w))?.matchups||{};for(const m of Object.values(wd)){if(!Array.isArray(m)||m.length<2)continue;const a=m.find(x=>Number(x.roster_id)===Number(id));if(a)return{team:a,opp:m.find(x=>Number(x.roster_id)!==Number(id))};}return null};
 const hist=(id,through=Number(displayWeek)-1)=>{let w=0,l=0,pf=0,res=[];for(let x=1;x<=through;x++){const g=game(id,x);if(!g)continue;const a=sum(g.team.points),b=sum(g.opp.points);pf+=a;if(a>b){w++;res.push('W')}else if(a<b){l++;res.push('L')}else res.push('T')}let streak=0,type=res.at(-1);for(let i=res.length-1;i>=0&&res[i]===type;i--)streak++;return{w,l,pf,g:res.length,ppg:res.length?pf/res.length:0,streak,type}};
 const standings=()=>{const ids=new Set();for(const m of matchupArray||[])for(const e of m||[])if(e?.roster_id!=null)ids.add(Number(e.roster_id));return[...ids].map(id=>({id,...hist(id)})).sort((a,b)=>(b.g?b.w/b.g:0)-(a.g?a.w/a.g:0)||b.pf-a.pf).map((x,i)=>({...x,rank:i+1}))};
 const priorMeeting=(a,b)=>{for(let w=Number(displayWeek)-1;w>=1;w--){const g=game(a,w);if(g&&Number(g.opp.roster_id)===Number(b)){const ap=sum(g.team.points),bp=sum(g.opp.points);return{week:w,a:ap,b:bp,winner:ap>bp?a:bp>ap?b:null,margin:n(Math.abs(ap-bp))}}return null};
 const build=()=>{if(Number(displayWeek)<2)return[];const st=standings(),stories=[];let gameOfWeek=null,best=-1;for(const m of matchupArray||[]){if(!m?.[0]||!m?.[1])continue;const a=m[0],b=m[1],A=team(a.roster_id),B=team(b.roster_id),ah=hist(a.roster_id),bh=hist(b.roster_id),ar=st.find(x=>x.id==a.roster_id)?.rank||99,br=st.find(x=>x.id==b.roster_id)?.rank||99,pa=n(proj(a)),pb=n(proj(b)),meeting=priorMeeting(a.roster_id,b.roster_id);let score=20-Math.abs(pa-pb)+Math.max(0,12-(ar+br));if(meeting)score+=5;if(score>best){best=score;gameOfWeek={label:'🏆 Game of the Week',text:`${A.name} vs ${B.name} gets the spotlight. The projection is ${pa}-${pb}${meeting?`, and these teams already have history from Week ${meeting.week}`:''}.`}}if(meeting&&meeting.winner){const loser=meeting.winner==a.roster_id?B:A,winner=meeting.winner==a.roster_id?A:B;stories.push({p:8,label:'🔥 Revenge Game',text:`${loser.name} gets another shot at ${winner.name} after losing their Week ${meeting.week} meeting by ${meeting.margin}.`});stories.push({p:6,label:'🧹 Season Sweep Watch',text:`${winner.name} already owns one win over ${loser.name} this season and can complete the season sweep.`})}if((ah.type==='W'&&ah.streak>=2&&bh.type==='L'&&bh.streak>=2)||(bh.type==='W'&&bh.streak>=2&&ah.type==='L'&&ah.streak>=2)){const hot=ah.type==='W'?A:B,cold=ah.type==='L'?A:B;stories.push({p:7,label:'📈 Hot vs. Cold',text:`${hot.name} enters on a ${ah.type==='W'?ah.streak:bh.streak}-game winning streak while ${cold.name} has dropped ${ah.type==='L'?ah.streak:bh.streak} straight.`})}if(ar<=2&&br>=st.length-2||br<=2&&ar>=st.length-2){const giant=ar<=2?A:B,killer=ar<=2?B:A;stories.push({p:7,label:'👑 Giant Killer Opportunity',text:`${killer.name} gets a chance to shake up the league by knocking off ${giant.name}, currently one of the top teams in the standings.`})}if(ah.g>=2&&bh.g>=2&&ah.ppg>0&&bh.ppg>0){const avg=(ah.ppg+bh.ppg)/2;if(avg>=Math.max(...st.map(x=>x.ppg))*0.88)stories.push({p:5,label:'💣 Shootout Alert',text:`${A.name} and ${B.name} bring two productive offenses into this matchup. Their combined scoring pace makes this a prime shootout candidate.`})}if(ar>=st.length-1&&br>=st.length-1)stories.push({p:5,label:'🗑️ Toilet Bowl Alert',text:`${A.name} and ${B.name} meet near the bottom of the standings. Somebody has to win this thing.`});const odd=[{h:ah,t:A,r:ar},{h:bh,t:B,r:br}].find(x=>x.h.g>=3&&((x.r<=3&&x.h.ppg<st.map(s=>s.ppg).sort((a,b)=>a-b)[Math.floor(st.length/2)])||(x.r>=st.length-2&&x.h.ppg>st.map(s=>s.ppg).sort((a,b)=>a-b)[Math.floor(st.length/2)])));if(odd)stories.push({p:4,label:'🎯 Prove-It Game',text:`${odd.t.name}'s record and scoring profile are telling different stories. Week ${displayWeek} is another chance to prove which one is real.`})}return[gameOfWeek,...stories.sort((a,b)=>b.p-a.p).slice(0,3)].filter(Boolean)};$: stories=build();
</script>
<style>.box{width:95%;max-width:900px;margin:-12px auto 24px;display:grid;gap:10px}.story{padding:14px 16px;border:1px solid var(--ccc);border-radius:14px;background:var(--fff);box-shadow:0 4px 14px rgba(0,0,0,.06)}.label{font-size:.72rem;font-weight:850;letter-spacing:.5px;text-transform:uppercase;opacity:.65;margin-bottom:5px}.text{font-size:.9rem;line-height:1.5;font-weight:600}@media(max-width:600px){.box{width:100%}.text{font-size:.82rem}}</style>
{#if stories.length}<section class="box">{#each stories as s}<div class="story"><div class="label">{s.label}</div><div class="text">{s.text}</div></div>{/each}</section>{/if}