<script>
 import {getAvatarFromTeamManagers,getTeamNameFromTeamManagers} from '$lib/utils/helperFunctions/universalFunctions';
 export let previousDrafts=[];export let leagueTeamManagers=[];export let players={};
 const drafts=(previousDrafts||[]).filter(d=>d?.draft?.length&&d?.draftOrder?.length).sort((a,b)=>+b.year-+a.year);let selectedYear=drafts[0]?.year;
 $: selected=drafts.find(d=>String(d.year)===String(selectedYear));$: analysis=selected?analyze(selected):null;
 const externalLists={
  2025:['Josh Allen','Lamar Jackson','Jayden Daniels','Jalen Hurts','Joe Burrow','Patrick Mahomes II','JaMarr Chase','Bijan Robinson','Baker Mayfield','Saquon Barkley','Bo Nix','CeeDee Lamb','Justin Jefferson','Jahmyr Gibbs','Kyler Murray','Dak Prescott','Nico Collins','Derrick Henry','Brian Thomas Jr','Malik Nabers','Justin Fields','Puka Nacua','Brock Purdy','Justin Herbert','Amon-Ra St Brown','Ashton Jeanty','Christian McCaffrey','Caleb Williams','Drake Maye','Jonathan Taylor','Drake London','Jared Goff','AJ Brown','Josh Jacobs','George Kittle','Jordan Love','Brock Bowers','Bucky Irving','Ladd McConkey','DeVon Achane','Kyren Williams','Trevor Lawrence','Chase Brown','Tee Higgins','CJ Stroud','Mike Evans','Trey McBride','James Cook','JJ McCarthy','Jaxon Smith-Njigba','Tyreek Hill','Davante Adams','Omarion Hampton','Marvin Harrison Jr','Kenneth Walker III','Garrett Wilson','Terry McLaurin','DK Metcalf','Breece Hall','Chuba Hubbard','Bryce Young','Tua Tagovailoa','James Conner','Courtland Sutton','TreVeyon Henderson','Jameson Williams','Alvin Kamara','DJ Moore','Geno Smith','Xavier Worthy','Michael Penix Jr','Matthew Stafford','Calvin Ridley','Tetairoa McMillan','George Pickens','DeVonta Smith','David Montgomery','DAndre Swift','Zay Flowers','Tony Pollard','RJ Harvey','Sam LaPorta','Isiah Pacheco','Cam Ward','Sam Darnold','Jaylen Waddle','Aaron Jones Sr','Mark Andrews','Kaleb Johnson','Travis Hunter','TJ Hockenson','Tyrone Tracy Jr','Ricky Pearsall','Rome Odunze','Rashee Rice','Chris Olave','Jordan Mason','Jerry Jeudy','Emeka Egbuka','Travis Kelce'],
  2024:['Josh Allen','Jalen Hurts','Patrick Mahomes II','Lamar Jackson','Anthony Richardson','CJ Stroud','Christian McCaffrey','Kyler Murray','CeeDee Lamb','Tyreek Hill','Joe Burrow','JaMarr Chase','Dak Prescott','Breece Hall','Bijan Robinson','Amon-Ra St Brown','Jordan Love','Justin Jefferson','AJ Brown','Jayden Daniels','Garrett Wilson','Brock Purdy','Jonathan Taylor','Jahmyr Gibbs','Caleb Williams','Puka Nacua','Tua Tagovailoa','Saquon Barkley','Jared Goff','Marvin Harrison Jr','Trevor Lawrence','Derrick Henry','Drake London','Kyren Williams','Davante Adams']
 };
 const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'').replace(/(jr|sr|ii|iii)$/,'');
 const rankMap=y=>Object.fromEntries((externalLists[y]||[]).map((n,i)=>[norm(n),i+1]));
 function rp(d,r,c){let R=r+1,n=d.draftOrder.length;if(d.draftType==='snake'&&!d.reversalRound)return R%2===0?n-c:c+1;if(d.draftType==='snake'&&d.reversalRound){if((R<d.reversalRound&&R%2===0)||(R>=d.reversalRound&&R%2===1))return n-c;return c+1}return(!d.reversalRound||R<d.reversalRound)?c+1:n-c}
 function flatten(d){let n=d.draftOrder.length,o=[];d.draft.forEach((row,r)=>row.forEach((x,c)=>{if(!x?.player)return;let q=rp(d,r,c),p=players?.[x.player]||{},name=`${p.fn||''} ${p.ln||''}`.trim()||'Unknown Player';o.push({owner:x.newOwner||d.draftOrder[c],pos:p.pos||'UNK',name,round:r+1,roundPick:q,overall:r*n+q})}));return o}
 function letter(s){if(s>=94)return'A+';if(s>=90)return'A';if(s>=87)return'A-';if(s>=83)return'B+';if(s>=80)return'B';if(s>=77)return'B-';if(s>=73)return'C+';if(s>=70)return'C';if(s>=67)return'C-';if(s>=63)return'D+';if(s>=60)return'D';return'F'}
 function posGrade(posPicks,need){let n=posPicks.length;if(n>=need+2)return'A';if(n>=need+1)return'B+';if(n>=need)return'B';if(n===need-1)return'C';return'D'}
 function verdict(s,best,reach,counts){let base=s>=90?'Excellent draft-day value with a strong overall build.':s>=83?'A strong draft with more wins than misses.':s>=77?'A solid draft that mixed good value with a few meaningful risks.':s>=70?'An average draft that will need several picks to outperform cost.':'A risky draft with notable value and roster-construction concerns.';if(best?.delta>=15)base+=` The biggest win was ${best.name}, who fell well past FantasyPros value.`;if(reach?.delta<=-15)base+=` The biggest concern was paying a premium for ${reach.name}.`;if(counts.QB<2)base+=' The 2-QB requirement creates an additional structural weakness.';return base}
 function score(t,y){let s=75,good=[],bad=[],by=p=>t.picks.filter(x=>x.pos===p),qb=by('QB'),rb=by('RB'),wr=by('WR'),te=by('TE'),k=by('K'),def=by('DEF'),map=rankMap(y);
  const valued=t.picks.map(p=>({...p,ext:map[norm(p.name)]})).filter(p=>p.ext);const weighted=valued.map(p=>{let w=p.round<=3?1.5:p.round<=6?1:0.65;return{...p,delta:p.ext-p.overall,w}});let wsum=weighted.reduce((a,p)=>a+p.w,0),avg=wsum?weighted.reduce((a,p)=>a+p.delta*p.w,0)/wsum:0;s+=Math.max(-14,Math.min(14,avg/2.5));
  const best=[...weighted].sort((a,b)=>b.delta-a.delta)[0],reach=[...weighted].sort((a,b)=>a.delta-b.delta)[0];if(best?.delta>=8)good.push(`${best.name} was +${Math.round(best.delta)} picks of value vs FantasyPros`);if(reach?.delta<=-8)bad.push(`${reach.name} went ${Math.abs(Math.round(reach.delta))} picks ahead of FantasyPros`);
  if(qb.length>=2)s+=3;else{s-=12;bad.push('Did not draft two starting QBs')};if(qb.length>=3)s+=1;if(rb.length>=3)s+=2;else{s-=3;bad.push('Thin RB room')};if(wr.length>=4)s+=3;else if(wr.length<3){s-=4;bad.push('Thin WR room')};if(te.length)s+=2;else{s-=4;bad.push('No TE drafted')};if(t.picks.some(x=>['K','DEF'].includes(x.pos)&&x.round<=8)){s-=3;bad.push('Early/mid-round pick spent on K/DEF')}
  if(!good.length)good.push('Roster construction stayed reasonably balanced');s=Math.max(45,Math.min(96,Math.round(s)));let counts={QB:qb.length,RB:rb.length,WR:wr.length,TE:te.length,K:k.length,DEF:def.length};let grades={QB:posGrade(qb,2),RB:posGrade(rb,3),WR:posGrade(wr,4),TE:posGrade(te,1)};let early=t.picks.filter(x=>x.round<=6).map(x=>`${x.round}.${String(x.roundPick).padStart(2,'0')} ${x.pos}`).join(' · ');return{...t,score:s,grade:letter(s),good:good.slice(0,3),bad:bad.slice(0,3),counts,best,reach,coverage:valued.length,grades,early,verdict:verdict(s,best,reach,counts)}}
 function analyze(d){let picks=flatten(d),teams=d.draftOrder.filter(Boolean).map(id=>({rosterID:id,picks:picks.filter(p=>String(p.owner)===String(id))})),out=teams.map(t=>score(t,+d.year)).sort((a,b)=>b.score-a.score);return{teams:out,top:out.slice(0,3),sourceCount:(externalLists[+d.year]||[]).length}}
 const pick=p=>p?`${p.round}.${String(p.roundPick).padStart(2,'0')}`:'—';
</script>
<div class="wrap"><section class="intro"><h2>🧠 GGL Draft Report Cards</h2><p>Grades compare actual GGL picks against <strong>FantasyPros preseason Superflex rankings</strong> for that season, then adjust for full-roster construction and GGL's true 2-QB requirement.</p></section>
{#if drafts.length}<nav>{#each drafts as d}<button class:active={String(selectedYear)===String(d.year)} onclick={()=>selectedYear=d.year}>{d.year}</button>{/each}</nav>{/if}
{#if analysis}<div class="source">FantasyPros benchmark coverage: top {analysis.sourceCount} preseason Superflex players for {selectedYear}</div><h3>{selectedYear} Draft Grades</h3><div class="top">{#each analysis.top as t,i}<div><b>#{i+1}</b> {getTeamNameFromTeamManagers(leagueTeamManagers,t.rosterID,selectedYear)} <strong>{t.grade}</strong></div>{/each}</div><div class="grid">{#each analysis.teams as t}<article><header><img src={getAvatarFromTeamManagers(leagueTeamManagers,t.rosterID,selectedYear)} alt=""><span><b>{getTeamNameFromTeamManagers(leagueTeamManagers,t.rosterID,selectedYear)}</b><small>{t.coverage} picks matched to FantasyPros rankings</small></span><em>{t.grade}<small>{t.score}/100</small></em></header><div class="pos">{#each Object.entries(t.counts) as [p,c]}{#if c}<span>{p} <b>{c}</b></span>{/if}{/each}</div><div class="subgrades"><span>QB <b>{t.grades.QB}</b></span><span>RB <b>{t.grades.RB}</b></span><span>WR <b>{t.grades.WR}</b></span><span>TE <b>{t.grades.TE}</b></span></div><div class="values">{#if t.best}<div><small>Best FantasyPros value</small><b>{t.best.name} · {pick(t.best)}</b><span>+{Math.round(t.best.delta)} picks</span></div>{/if}{#if t.reach}<div><small>Biggest reach</small><b>{t.reach.name} · {pick(t.reach)}</b><span>{Math.abs(Math.round(t.reach.delta))} picks early</span></div>{/if}</div><div class="early"><small>Early-round build</small><p>{t.early}</p></div><div class="notes"><section><h4>Strengths</h4>{#each t.good as x}<p>✓ {x}</p>{/each}</section><section><h4>Needs work</h4>{#if t.bad.length}{#each t.bad as x}<p>• {x}</p>{/each}{:else}<p>• No major flags</p>{/if}</section></div><div class="verdict"><small>Draft verdict</small><p>{t.verdict}</p></div></article>{/each}</div><p class="method">FantasyPros value is weighted most heavily in the early rounds. Positional grades evaluate depth and starter coverage; the overall grade combines market value with roster construction. Historical drafts are judged against preseason expectations from that season, not hindsight.</p>{/if}</div>
<style>.wrap{width:95%;max-width:1100px;margin:auto}.intro,article,.top>div{border:1px solid var(--ccc);background:var(--fff);border-radius:16px}.intro{padding:18px}.intro h2{margin:0}.intro p{margin:8px 0 0;line-height:1.5;opacity:.7}nav{display:flex;gap:8px;margin:14px 0}nav button{border:1px solid var(--ccc);border-radius:999px;padding:8px 14px;background:var(--fff);color:inherit;font-weight:800}nav button.active{background:var(--blueOne);color:#fff}.source{font-size:.65rem;opacity:.55;margin:2px 0 12px}.top{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:14px}.top>div{padding:12px;font-size:.75rem}.top strong{float:right;font-size:1.2rem}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}article{padding:15px}header{display:flex;align-items:center;gap:9px}header img{width:40px;height:40px;border-radius:50%;object-fit:cover}header span{flex:1;min-width:0}header span b,header small{display:block}header span b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.85rem}header small{font-size:.58rem;opacity:.55;margin-top:2px}header em{font-style:normal;font-weight:950;font-size:1.55rem;text-align:center}.pos,.subgrades{display:flex;gap:5px;flex-wrap:wrap;margin-top:12px}.pos span,.subgrades span{border:1px solid var(--ccc);border-radius:999px;padding:5px 8px;font-size:.61rem}.subgrades{margin-top:7px}.subgrades span{background:var(--f3f3f3)}.values{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.values>div,.early,.verdict{padding:10px;background:var(--f3f3f3);border-radius:11px}.values small,.early small,.verdict small{font-size:.58rem;text-transform:uppercase;letter-spacing:.5px;opacity:.5}.values b,.values span{display:block}.values b{font-size:.67rem;margin-top:4px}.values span{font-size:.6rem;margin-top:3px;opacity:.65}.early{margin-top:8px}.early p,.verdict p{font-size:.66rem;line-height:1.45;margin:5px 0 0}.notes{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.notes h4{margin:0 0 5px;font-size:.6rem;text-transform:uppercase;opacity:.5}.notes p{font-size:.66rem;line-height:1.4;margin:4px 0}.verdict{margin-top:12px}.method{text-align:center;font-size:.64rem;opacity:.55;margin:16px}.wrap>h3{margin:16px 0 10px}@media(max-width:700px){.grid,.top{grid-template-columns:1fr}.notes,.values{grid-template-columns:1fr}.wrap{width:98%}}</style>