<script>
 import {getAvatarFromTeamManagers,getTeamNameFromTeamManagers} from '$lib/utils/helperFunctions/universalFunctions';
 export let previousDrafts=[];export let leagueTeamManagers=[];export let players={};
 const drafts=(previousDrafts||[]).filter(d=>d?.draft?.length&&d?.draftOrder?.length).sort((a,b)=>+b.year-+a.year);let selectedYear=drafts[0]?.year;
 $: selected=drafts.find(d=>String(d.year)===String(selectedYear));$: analysis=selected?analyze(selected):null;
 const med=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
 function rp(d,r,c){let R=r+1,n=d.draftOrder.length;if(d.draftType==='snake'&&!d.reversalRound)return R%2===0?n-c:c+1;if(d.draftType==='snake'&&d.reversalRound){if((R<d.reversalRound&&R%2===0)||(R>=d.reversalRound&&R%2===1))return n-c;return c+1}return(!d.reversalRound||R<d.reversalRound)?c+1:n-c}
 function flatten(d){let n=d.draftOrder.length,o=[];d.draft.forEach((row,r)=>row.forEach((x,c)=>{if(!x?.player)return;let q=rp(d,r,c),p=players?.[x.player]||{};o.push({owner:x.newOwner||d.draftOrder[c],pos:p.pos||'UNK',round:r+1,roundPick:q,overall:r*n+q})}));return o}
 function letter(s){if(s>=94)return'A+';if(s>=90)return'A';if(s>=87)return'A-';if(s>=83)return'B+';if(s>=80)return'B';if(s>=77)return'B-';if(s>=73)return'C+';if(s>=70)return'C';if(s>=67)return'C-';if(s>=63)return'D+';if(s>=60)return'D';return'F'}
 function score(t,b,n){let s=72,good=[],bad=[],by=p=>t.picks.filter(x=>x.pos===p),qb=by('QB'),rb=by('RB'),wr=by('WR'),te=by('TE'),k=by('K'),def=by('DEF'),early=t.picks.filter(x=>x.round<=6);
  if(qb.length>=2){s+=6;good.push('Filled both required QB starter spots')}else{s-=18;bad.push('Did not draft two starting QBs')};if(qb.length>=3){s+=3;good.push('Added QB insurance')};if(qb[1]&&b.qb2&&qb[1].overall>b.qb2+n*1.5){s-=4;bad.push('Waited well past the GGL market for QB2')}
  if(rb.length>=3){s+=5;good.push('Built useful RB depth')}else{s-=5;bad.push('Thin RB room')};if(wr.length>=4){s+=6;good.push('Built strong WR depth')}else if(wr.length>=3)s+=2;else{s-=6;bad.push('Thin WR room')};if(te.length)s+=4;else{s-=6;bad.push('No TE drafted')}
  let skill=early.filter(x=>['RB','WR','TE'].includes(x.pos)).length;if(skill>=4){s+=5;good.push('Premium picks invested in skill-position starters')}else if(skill<=2){s-=4;bad.push('Limited early RB/WR/TE investment')};let spread=new Set(early.map(x=>x.pos).filter(x=>['QB','RB','WR','TE'].includes(x))).size;if(spread>=3)s+=4;else{s-=3;bad.push('Early picks concentrated at too few positions')}
  if(k.length>1){s-=2;bad.push('Multiple kicker picks')};if(def.length>1){s-=2;bad.push('Multiple defense picks')};if(t.picks.some(x=>['K','DEF'].includes(x.pos)&&x.round<=8)){s-=3;bad.push('Early/mid-round capital spent on K/DEF')};s=Math.max(45,Math.min(98,Math.round(s)));
  let counts={QB:qb.length,RB:rb.length,WR:wr.length,TE:te.length,K:k.length,DEF:def.length},identity='Balanced draft';if(wr.length>=5&&wr.length>=rb.length)identity='WR-heavy build';else if(rb.length>=5)identity='RB-heavy build';else if(qb.filter(x=>x.round<=5).length>=2)identity='Early-QB build';return{...t,score:s,grade:letter(s),good:good.slice(0,3),bad:bad.slice(0,3),counts,identity,qb1:qb[0],qb2:qb[1]}}
 function analyze(d){let picks=flatten(d),teams=d.draftOrder.filter(Boolean).map(id=>({rosterID:id,picks:picks.filter(p=>String(p.owner)===String(id))})),b={qb1:med(teams.map(t=>t.picks.filter(p=>p.pos==='QB')[0]?.overall)),qb2:med(teams.map(t=>t.picks.filter(p=>p.pos==='QB')[1]?.overall))},out=teams.map(t=>score(t,b,d.draftOrder.length)).sort((a,b)=>b.score-a.score);return{teams:out,top:out.slice(0,3)}}
 const pick=p=>p?`${p.round}.${String(p.roundPick).padStart(2,'0')}`:'—';
</script>
<div class="wrap"><section class="intro"><h2>🧠 GGL Draft Report Cards</h2><p>Full-team grades based on <strong>all positions</strong>, starter coverage, depth, early-round allocation and roster balance. GGL's <strong>2-QB format</strong> is accounted for as a league rule, not treated as the whole analysis.</p></section>
{#if drafts.length}<nav>{#each drafts as d}<button class:active={String(selectedYear)===String(d.year)} onclick={()=>selectedYear=d.year}>{d.year}</button>{/each}</nav>{/if}
{#if analysis}<h3>{selectedYear} Draft Grades</h3><div class="top">{#each analysis.top as t,i}<div><b>#{i+1}</b> {getTeamNameFromTeamManagers(leagueTeamManagers,t.rosterID,selectedYear)} <strong>{t.grade}</strong></div>{/each}</div><div class="grid">{#each analysis.teams as t}<article><header><img src={getAvatarFromTeamManagers(leagueTeamManagers,t.rosterID,selectedYear)} alt=""><span><b>{getTeamNameFromTeamManagers(leagueTeamManagers,t.rosterID,selectedYear)}</b><small>{t.identity}</small></span><em>{t.grade}<small>{t.score}/100</small></em></header><div class="pos">{#each Object.entries(t.counts) as [p,c]}{#if c}<span>{p} <b>{c}</b></span>{/if}{/each}</div><div class="qb"><span>2-QB context</span><b>QB1 {pick(t.qb1)} · QB2 {pick(t.qb2)}</b></div><div class="notes"><section><h4>Strengths</h4>{#each t.good as x}<p>✓ {x}</p>{/each}</section><section><h4>Needs work</h4>{#each t.bad as x}<p>• {x}</p>{/each}</section></div></article>{/each}</div><p class="method">Historical grades currently measure draft-day roster construction. The 2026 version can add current player-value/ADP data for individual steals and reaches.</p>{/if}</div>
<style>.wrap{width:95%;max-width:1100px;margin:auto}.intro,article,.top>div{border:1px solid var(--ccc);background:var(--fff);border-radius:16px}.intro{padding:18px}.intro h2{margin:0}.intro p{margin:8px 0 0;line-height:1.5;opacity:.7}nav{display:flex;gap:8px;margin:14px 0}nav button{border:1px solid var(--ccc);border-radius:999px;padding:8px 14px;background:var(--fff);color:inherit;font-weight:800}nav button.active{background:var(--blueOne);color:#fff}.top{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:14px}.top>div{padding:12px;font-size:.75rem}.top strong{float:right;font-size:1.2rem}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}article{padding:15px}header{display:flex;align-items:center;gap:9px}header img{width:40px;height:40px;border-radius:50%;object-fit:cover}header span{flex:1;min-width:0}header span b,header small{display:block}header span b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.85rem}header small{font-size:.58rem;opacity:.55;margin-top:2px}header em{font-style:normal;font-weight:950;font-size:1.55rem;text-align:center}.pos{display:flex;gap:5px;flex-wrap:wrap;margin-top:12px}.pos span{border:1px solid var(--ccc);border-radius:999px;padding:5px 8px;font-size:.61rem}.qb{display:flex;justify-content:space-between;margin-top:10px;padding:9px;background:var(--f3f3f3);border-radius:10px;font-size:.64rem}.qb span{opacity:.55}.notes{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.notes h4{margin:0 0 5px;font-size:.6rem;text-transform:uppercase;opacity:.5}.notes p{font-size:.66rem;line-height:1.4;margin:4px 0}.method{text-align:center;font-size:.64rem;opacity:.55;margin:16px}.wrap>h3{margin:16px 0 10px}@media(max-width:700px){.grid,.top{grid-template-columns:1fr}.notes{grid-template-columns:1fr}.wrap{width:98%}}</style>